import { Entity, Column, ManyToOne, JoinColumn, Index } from 'typeorm';
import { BaseEntity } from '../../../common/entities/base.entity';
import { Category } from '../../category/entities/category.entity';

/**
 * Product entity - the final catalog item.
 * 
 * `sku` is auto-generated by SKU Engine at creation time.
 * `sku` is IMMUTABLE after creation (same inputs = same SKU always).
 * 
 * `attributeValues` stores what was used to generate the SKU as JSON.
 * This allows:
 * - Displaying product attributes in UI
 * - Regenerating/verifying SKU if needed
 * - Future filtering by attribute values
 */
@Entity('products')
export class Product extends BaseEntity {
  @Column({ type: 'varchar', length: 255 })
  title: string;

  @Column({ type: 'text', nullable: true })
  description: string;

  @Index({ unique: true })
  @Column({ type: 'varchar', length: 100 })
  sku: string;               // Auto-generated, globally unique, immutable

  @ManyToOne(() => Category, { eager: true, onDelete: 'RESTRICT' })
  @JoinColumn({ name: 'categoryId' })
  category: Category;

  @Column()
  categoryId: number;

  /**
   * Stores the attribute values used to generate the SKU.
   * Format: [{ attributeType: 'COLOR', code: 'whtclr', label: 'White Color' }]
   * Stored as JSON - queryable in MySQL 5.7+ / 8.x
   */
  @Column({ type: 'json', nullable: true })
  attributeValues: Record<string, any>[];

  @Column({ type: 'boolean', default: true })
  isActive: boolean;

  @Column({ type: 'text', nullable: true })
  notes: string;             // Internal notes, not shown to customers
}
